name: Auto Comment on PR

on:
  pull_request_target:
    types: [ opened, synchronize ]
    branches: [ main ]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT  }}
          script: |
            const { owner, repo, number: issue_number } = context.issue;
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: commentBody
            });
            github.rest.issues.addLabels({
                owner,
                repo,
                issue_number,
                labels: ['ready to review','auto merge']
              });
